// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: postgres_service.proto

package postgres_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserSClient is the client API for UserS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSClient interface {
	Create(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error)
	Update(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error)
	Get(ctx context.Context, in *IdMsg, opts ...grpc.CallOption) (*UserRes, error)
	Delete(ctx context.Context, in *IdMsg, opts ...grpc.CallOption) (*Empty, error)
	GetAll(ctx context.Context, in *GetAlluserParams, opts ...grpc.CallOption) (*GetAllUserResponse, error)
}

type userSClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSClient(cc grpc.ClientConnInterface) UserSClient {
	return &userSClient{cc}
}

func (c *userSClient) Create(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/postgresService.UserS/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSClient) Update(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/postgresService.UserS/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSClient) Get(ctx context.Context, in *IdMsg, opts ...grpc.CallOption) (*UserRes, error) {
	out := new(UserRes)
	err := c.cc.Invoke(ctx, "/postgresService.UserS/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSClient) Delete(ctx context.Context, in *IdMsg, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/postgresService.UserS/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userSClient) GetAll(ctx context.Context, in *GetAlluserParams, opts ...grpc.CallOption) (*GetAllUserResponse, error) {
	out := new(GetAllUserResponse)
	err := c.cc.Invoke(ctx, "/postgresService.UserS/Get_all", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSServer is the server API for UserS service.
// All implementations must embed UnimplementedUserSServer
// for forward compatibility
type UserSServer interface {
	Create(context.Context, *UserReq) (*UserRes, error)
	Update(context.Context, *UserReq) (*UserRes, error)
	Get(context.Context, *IdMsg) (*UserRes, error)
	Delete(context.Context, *IdMsg) (*Empty, error)
	GetAll(context.Context, *GetAlluserParams) (*GetAllUserResponse, error)
	mustEmbedUnimplementedUserSServer()
}

// UnimplementedUserSServer must be embedded to have forward compatible implementations.
type UnimplementedUserSServer struct {
}

func (UnimplementedUserSServer) Create(context.Context, *UserReq) (*UserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedUserSServer) Update(context.Context, *UserReq) (*UserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedUserSServer) Get(context.Context, *IdMsg) (*UserRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedUserSServer) Delete(context.Context, *IdMsg) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedUserSServer) GetAll(context.Context, *GetAlluserParams) (*GetAllUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedUserSServer) mustEmbedUnimplementedUserSServer() {}

// UnsafeUserSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSServer will
// result in compilation errors.
type UnsafeUserSServer interface {
	mustEmbedUnimplementedUserSServer()
}

func RegisterUserSServer(s grpc.ServiceRegistrar, srv UserSServer) {
	s.RegisterService(&UserS_ServiceDesc, srv)
}

func _UserS_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresService.UserS/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSServer).Create(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserS_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresService.UserS/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSServer).Update(ctx, req.(*UserReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserS_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresService.UserS/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSServer).Get(ctx, req.(*IdMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserS_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdMsg)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresService.UserS/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSServer).Delete(ctx, req.(*IdMsg))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserS_GetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlluserParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSServer).GetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/postgresService.UserS/Get_all",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSServer).GetAll(ctx, req.(*GetAlluserParams))
	}
	return interceptor(ctx, in, info, handler)
}

// UserS_ServiceDesc is the grpc.ServiceDesc for UserS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "postgresService.UserS",
	HandlerType: (*UserSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _UserS_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserS_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _UserS_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserS_Delete_Handler,
		},
		{
			MethodName: "Get_all",
			Handler:    _UserS_GetAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "postgres_service.proto",
}
